import type { HerohubReport } from './types'

export const sampleReport: HerohubReport = {
  reportTitle: 'Herohub Talent & Operating Roadmap',
  reportSubtitle: '12-Month Dealer Independence, Leadership Development & Profitability Plan',
  profile: {
    name: 'Honda Suzuki of Sanford',
    brands: ['Honda', 'Suzuki', 'Kymco', 'SSR Motorsports', 'Segway Powersports US', 'Beta Motorcycles USA'],
    locations: '1',
    employees: 'Under 15',
    dealerPrincipal: 'Cliff Barker',
    generalManager: 'Daniel Barker',
    planningHorizon: '12 months',
    roadmapStart: 'August 2026 — assumption based on current planning date',
  },
  purpose: 'Build a stronger operating system supported by Herohub with stronger leadership ownership, clearer decision-making authority, improved department profitability, consistent employee development, repeatable onboarding systems, and less dependence on the Dealer Principal for daily operations.',
  successDefinition: 'To be able to take more time off and not worry about the day-to-day operations of the dealership.',
  strategicAim: 'Build an operating system that creates owner independence through stronger leadership accountability and repeatable dealership systems.',
  executiveSummary: 'Honda Suzuki of Sanford has a strong foundation of dealership experience, OEM training exposure, and experienced employees. The greatest opportunity is not simply adding training programs, but creating a more intentional operating structure where managers own outcomes and employees have clearer development paths.',
  priorities: [
    'Increase service department profitability',
    'Increase F&I profitability',
    'Increase parts department profitability',
    'Improve technician efficiency',
    'Improve hiring and training capability',
  ],
  leadershipRead: 'The opportunity is not simply more training. It is transferring dealership knowledge, decisions, and accountability into systems that can operate without constant Dealer Principal involvement.',
  strengths: [
    { title: 'Experienced Leadership Foundation', fact: 'Cliff Barker has 24 years of dealership experience and the leadership team has significant department experience.', opportunity: 'Transfer knowledge into systems so dealership success is less dependent on one individual.' },
    { title: 'Existing OEM Training Culture', fact: 'Current formal training includes OEM Product Training, OEM Sales Certification, and Technician Certification.', opportunity: 'Expand from technical knowledge development into leadership systems and operating habits.' },
    { title: 'Clear Awareness of Business Priorities', fact: 'The dealership has specifically identified Service, F&I, and Parts as profitability opportunities.', opportunity: 'Use the clarity of those priorities to focus development and operating efforts.' },
  ],
  opportunities: [
    { title: 'Reduce owner dependency', businessChange: 'Managers take ownership of decisions and outcomes', priority: 'REQUIRED' },
    { title: 'Strengthen sales leadership', businessChange: 'Sales Manager role clarity and leadership capability', priority: 'REQUIRED' },
    { title: 'Create onboarding process', businessChange: 'New employees enter through a consistent system', priority: 'REQUIRED' },
    { title: 'Improve service profitability', businessChange: 'Stronger service operating cadence', priority: 'REQUIRED' },
    { title: 'Improve parts profitability', businessChange: 'Better process and customer experience execution', priority: 'RECOMMENDED' },
    { title: 'Improve F&I profitability', businessChange: 'Consistent process and accountability', priority: 'RECOMMENDED' },
  ],
  leaders: [
    { name: 'Cliff Barker', role: 'Dealer Principal / Manager', objective: 'Reduce operational dependency and strengthen leadership system', development: 'Herohub Unlimited; HerohubU leadership development', cadence: 'Monthly operating review', evidence: 'Decisions delegated, absence testing completed, fewer daily operational interruptions', decisionGate: '' },
    { name: 'Daniel Barker', role: 'General Manager', objective: 'Build dealership operating ownership', development: 'Herohub Unlimited; HerohubU leadership pathway', cadence: 'Weekly leadership alignment', evidence: 'Owns operating meetings, follow-up process, and accountability routines', decisionGate: '' },
    { name: 'Vann Gibson', role: 'Sales Manager', objective: 'Clarify and strengthen sales leadership effectiveness', development: 'Herohub Bootcamp; HerohubU leadership pathway', cadence: 'Sales coaching and 60-day review', evidence: 'Sales meetings, coaching activity, accountability conversations, salesperson development', decisionGate: 'Is Vann operating effectively as Sales Manager, or primarily as a senior salesperson?' },
    { name: 'Josh Higdon', role: 'Service Manager', objective: 'Increase service profitability', development: 'HerohubU leadership pathway', cadence: 'Weekly service review', evidence: 'Service workflow improvements and productivity review established', decisionGate: '' },
    { name: 'Jason Baker', role: 'Parts Manager', objective: 'Improve parts department profitability', development: 'HerohubU leadership pathway; HerohubIQ if customer-facing duties apply', cadence: 'Monthly parts review', evidence: 'Process improvements documented', decisionGate: '' },
    { name: 'Bill Mattson', role: 'Part-Time Sales Associate', objective: 'Improve customer engagement consistency', development: 'HerohubIQ', cadence: 'Sales coaching', evidence: 'Customer interaction improvement', decisionGate: '' },
    { name: 'Rusty Kerr', role: 'Full-Time Sales Associate', objective: 'Improve customer experience and sales consistency', development: 'HerohubIQ', cadence: 'Sales coaching', evidence: 'Improved process adherence', decisionGate: '' },
    { name: 'Jesse Fox', role: 'Full-Time Service A Tech', objective: 'Continue technical capability development', development: 'OEM/technical certification + manager coaching', cadence: 'Monthly development review', evidence: 'Certification progress and operational improvement', decisionGate: '' },
    { name: 'Donnie Dunlap', role: 'Full-Time Service B Tech', objective: 'Improve technical capability', development: 'OEM/technical certification + manager coaching', cadence: 'Monthly development review', evidence: 'Technical progression', decisionGate: '' },
    { name: 'Joe Cole', role: 'Full-Time Service C Tech', objective: 'Develop technical capability and future responsibility options', development: 'OEM/technical certification + manager coaching', cadence: 'Monthly development review', evidence: 'Skill progression documented', decisionGate: '' },
    { name: 'Allen Walker', role: 'Part-Time Service A Tech', objective: 'Support technical growth', development: 'OEM/technical certification as applicable + coaching', cadence: 'Monthly review', evidence: 'Skill progression', decisionGate: '' },
    { name: 'Blake Brown', role: 'Parts Counter Employee', objective: 'Improve customer-facing parts capability', development: 'HerohubIQ', cadence: 'Parts coaching', evidence: 'Improved customer interactions', decisionGate: '' },
  ],
  capacity: [
    { month: 'Aug 2026', classification: 'Shoulder / Peak', focus: 'Launch systems without disrupting customer demand', capacity: 'Limited' },
    { month: 'Sep 2026', classification: 'Shoulder', focus: 'Stabilize leadership routines', capacity: 'Moderate' },
    { month: 'Oct 2026', classification: 'Development', focus: 'Leadership development and process improvement', capacity: 'High' },
    { month: 'Nov 2026', classification: 'Development', focus: 'Profitability systems', capacity: 'High' },
    { month: 'Dec 2026', classification: 'Development', focus: 'Planning and onboarding preparation', capacity: 'Moderate' },
    { month: 'Jan 2027', classification: 'Development', focus: 'Leadership and operational improvements', capacity: 'High' },
    { month: 'Feb 2027', classification: 'Development', focus: 'Department improvement', capacity: 'Moderate' },
    { month: 'Mar 2027', classification: 'Shoulder', focus: 'Prepare for selling season', capacity: 'Limited' },
    { month: 'Apr 2027', classification: 'Peak', focus: 'Revenue execution', capacity: 'Reinforcement only' },
    { month: 'May 2027', classification: 'Peak', focus: 'Protect sales/service capacity', capacity: 'Reinforcement only' },
    { month: 'Jun 2027', classification: 'Peak', focus: 'Customer demand execution', capacity: 'Reinforcement only' },
    { month: 'Jul 2027', classification: 'Peak / Shoulder', focus: 'Review and prepare next cycle', capacity: 'Moderate' },
  ],
  roadmap: [
    { month: 'August 2026', title: 'Launch Operating System', classification: 'Shoulder / Peak Assumption', objective: 'Create immediate clarity around leadership expectations, development ownership, and dealership operating priorities.', owner: 'Daniel Barker / Leadership Team', actions: ['Launch Herohub Unlimited onboarding', 'Validate employee roster and responsibilities', 'Confirm development assignments', 'Establish manager expectations', 'Define KPI baseline requirements'], evidence: ['Access confirmed', 'Approved roster', 'Employees assigned', 'Leadership expectations documented', 'Baselines established'], developmentSupport: ['Why Buy From Honda Suzuki of Sanford? customer experience activity'] },
    { month: 'September 2026', title: 'Leadership Alignment & Role Clarity', classification: 'Shoulder', objective: 'Determine whether the Sales Manager role is functioning as a leadership position or primarily as an individual contributor role.', owner: 'Daniel Barker', actions: ['Review sales meeting ownership', 'Review coaching conversations', 'Review accountability conversations', 'Review sales process adherence', 'Gather team feedback'], evidence: ['Written Sales Manager expectations', 'Coaching schedule established', '60-day review completed'], developmentSupport: [] },
    { month: 'October 2026', title: 'Sales Leadership Capability Development', classification: 'Development', objective: 'Build stronger sales leadership capability and management routines.', owner: 'Daniel Barker', actions: ['Begin Herohub Bootcamp', 'Implement and reinforce learning', 'Begin HerohubU pathway', 'Continue HerohubIQ practice where applicable'], evidence: ['Sales meetings structured', 'Coaching process documented', 'Sales team expectations communicated'], developmentSupport: ['Herohub Bootcamp', 'HerohubU', 'HerohubIQ'] },
    { month: 'November 2026', title: 'Service Profitability Operating System', classification: 'Development', objective: 'Improve service profitability through stronger operating discipline.', owner: 'Josh Higdon', actions: ['Review service workflow', 'Identify technician efficiency barriers', 'Establish service review cadence'], evidence: ['Documented workflow', 'Improvement list', 'Monthly review completed'], developmentSupport: ['HerohubU leadership development', 'Manager-led operational coaching'] },
    { month: 'December 2026', title: 'Owner Independence System', classification: 'Development', objective: 'Reduce daily dependency on Cliff Barker.', owner: 'Cliff Barker', actions: ['Map decisions managers own', 'Define decisions requiring approval', 'Define escalation triggers'], evidence: ['Completed leadership responsibility map'], developmentSupport: [] },
    { month: 'January 2027', title: 'Build Hiring & Onboarding Capability', classification: 'Development', objective: 'Create a repeatable 30/60/90-day onboarding system before expected hiring activity.', owner: 'Daniel Barker', actions: ['Document role expectations', 'Create first-week checklist', 'Define training expectations', 'Create 30/60/90-day reviews'], evidence: ['Documented expectations', 'First-week checklist', 'Training plan', 'Review templates'], developmentSupport: [] },
    { month: 'February 2027', title: 'Parts Department Improvement', classification: 'Development', objective: 'Improve parts department profitability.', owner: 'Jason Baker', actions: ['Review parts customer process', 'Identify selling opportunities', 'Review department routines'], evidence: ['Process documented', 'Improvement plan', 'Monthly review'], developmentSupport: [] },
    { month: 'March 2027', title: 'Pre-Season Readiness', classification: 'Shoulder', objective: 'Ensure leadership systems function before peak demand.', owner: 'Leadership Team', actions: ['Review department scorecards', 'Confirm escalation rules', 'Review staffing needs'], evidence: ['Completed reviews', 'Escalation rules documented', 'Hiring decisions'], developmentSupport: [] },
    { month: 'April 2027', title: 'Peak Execution', classification: 'Peak Assumption', objective: 'Protect revenue generation.', owner: 'Department Managers', actions: ['Continue HerohubIQ practice', 'Continue manager coaching', 'Continue KPI reviews'], evidence: ['Reinforcement continues without disrupting peak activity'], developmentSupport: ['No intensive learning programs'] },
    { month: 'May 2027', title: 'Peak Execution', classification: 'Peak Assumption', objective: 'Execute customer experience and profitability priorities during peak demand.', owner: 'Department Managers', actions: ['Sales: reinforce customer process', 'Service: reinforce workflow', 'Parts: reinforce customer support'], evidence: ['Department review completed'], developmentSupport: [] },
    { month: 'June 2027', title: 'Independence Testing', classification: 'Peak Assumption', objective: 'Validate whether dealership operations continue without Cliff’s daily involvement.', owner: 'Cliff Barker / Daniel Barker', actions: ['Conduct absence test', 'Track escalations', 'Review manager updates'], evidence: ['Decisions handled appropriately', 'Escalations tracked', 'Managers provide updates independently'], developmentSupport: [] },
    { month: 'July 2027', title: 'Annual Review & Next-Year Planning', classification: 'Peak / Shoulder Assumption', objective: 'Review leadership ownership, development progress, profitability systems, and succession readiness.', owner: 'Leadership Team', actions: ['Review manager accountability', 'Review development completion', 'Review department systems', 'Discuss succession readiness'], evidence: ['Annual review completed', 'Next-year priorities established'], developmentSupport: [] },
  ],
  first30Days: [
    { timing: 'Week 1', action: 'Confirm roadmap priorities', owner: 'Cliff Barker', evidence: 'Leadership alignment' },
    { timing: 'Week 1', action: 'Launch Herohub Unlimited', owner: 'Daniel Barker', evidence: 'Access complete' },
    { timing: 'Week 1', action: 'Validate roster', owner: 'Daniel Barker', evidence: 'Approved roster' },
    { timing: 'Week 1–2', action: 'Assign employee development', owner: 'Daniel Barker', evidence: 'Assignments complete' },
    { timing: 'Weeks 2–4', action: 'Establish KPI baselines', owner: 'Managers', evidence: 'Baseline report' },
    { timing: 'Week 2', action: 'Conduct Why Buy From Honda Suzuki of Sanford?', owner: 'Daniel Barker', evidence: 'Scores documented' },
    { timing: 'Week 3', action: 'Establish coaching cadence', owner: 'Managers', evidence: 'Calendar established' },
    { timing: 'Week 4', action: 'Begin onboarding system design', owner: 'Daniel Barker', evidence: 'Draft completed' },
  ],
  scorecard: [
    { area: 'Leadership independence', indicator: 'Decisions completed without unnecessary escalation', owner: 'Daniel' },
    { area: 'Sales leadership', indicator: 'Coaching completed', owner: 'Sales Manager' },
    { area: 'Service performance', indicator: 'Workflow reviews completed', owner: 'Josh' },
    { area: 'Parts execution', indicator: 'Process reviews completed', owner: 'Jason' },
    { area: 'Employee development', indicator: 'Assignments completed', owner: 'Managers' },
  ],
  quarterlyQuestions: [
    'Are managers owning decisions?',
    'Is Dealer Principal dependency decreasing?',
    'Are department leaders improving operating discipline?',
    'Are hiring needs supported by onboarding systems?',
    'Are development activities producing observable behavior change?',
  ],
  decisions: [
    { decision: 'Confirm roadmap start month', owner: 'Cliff Barker', timing: 'Before launch', evidence: 'Approved start date' },
    { decision: 'Complete Sales Manager decision gate', owner: 'Cliff + Daniel', timing: 'First 60 days', evidence: 'Leadership evidence' },
    { decision: 'Establish KPI baselines', owner: 'Managers', timing: 'Month 1', evidence: 'Baseline data' },
    { decision: 'Finalize hiring needs', owner: 'Leadership Team', timing: 'Quarterly', evidence: 'Capacity review' },
    { decision: 'Validate succession progress', owner: 'Leadership Team', timing: 'Quarterly', evidence: 'Readiness review' },
  ],
  finalOutcomes: [
    'A clearer leadership operating structure',
    'Reduced Dealer Principal dependency',
    'Managers accountable for department outcomes',
    'A repeatable onboarding system',
    'Improved service, parts, and F&I operating discipline',
    'Employees with defined development paths',
    'A dealership capable of operating effectively when the Dealer Principal steps away from daily activities',
  ],
  closingStatement: 'This roadmap is designed as a dealership operating and talent plan supported by Herohub — not a training calendar.',
  sourceNotes: ['Seasonality classifications are assumptions in the source and should be validated against dealership-specific historical sales, service, and staffing data.'],
}
